<Window
    x:Class="Converter.Mvvm.View.ExceptionView"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:viewModel="clr-namespace:Converter.Mvvm.ViewModel"
    Title="{Binding WindowTitle}"
    Width="350"
    Height="120"
    Background="#FF2E2E2E"
    DataContext="{DynamicResource ExceptionViewModel}"
    FocusManager.FocusedElement="{Binding ElementName=CloseBtn}"
    SizeToContent="Height"
    WindowStartupLocation="CenterOwner">
    <Window.Resources>
        <viewModel:ExceptionViewModel x:Key="ExceptionViewModel" />
    </Window.Resources>
    <Window.InputBindings>
        <KeyBinding Key="Escape" Command="{Binding CloseWindowCommand}" />
    </Window.InputBindings>
    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="Auto" />
            <RowDefinition Height="Auto" />
            <RowDefinition Height="Auto" />
        </Grid.RowDefinitions>
        <TextBlock
            Grid.Row="0"
            HorizontalAlignment="Center"
            FontWeight="Bold"
            Foreground="Azure">
            Exception occurs:
        </TextBlock>
        <TextBlock
            Grid.Row="1"
            Margin="5,0,5,5"
            Padding="0"
            HorizontalAlignment="Center"
            Foreground="Azure"
            TextWrapping="Wrap">
            <Run Text="{Binding ExceptionText}" />
        </TextBlock>
        <StackPanel
            Grid.Row="2"
            Margin="5"
            HorizontalAlignment="Center"
            Orientation="Horizontal">
            <Button
                Name="CloseBtn"
                Command="{Binding CloseWindowCommand}"
                Content="Close"
                Foreground="MediumSpringGreen"
                Style="{StaticResource BtnStyle}"
                ToolTip="Close" />
        </StackPanel>
    </Grid>
</Window>

